import 'package:flutter/material.dart';

/// Centralized i18n system mirroring React i18next with ID/EN/NL locales.
class AppLocalizations extends ChangeNotifier {
  String _locale = 'id';
  String get locale => _locale;

  void setLocale(String l) {
    _locale = l;
    notifyListeners();
  }

  String t(String key) {
    final map = _locale == 'en' ? _en : _locale == 'nl' ? _nl : _id;
    return map[key] ?? key;
  }

  // ─── Indonesian ────────────────────────────────────────
  static const _id = <String, String>{
    // nav
    'nav.back_to_home': 'Kembali ke Beranda',
    'nav.dashboard': 'Dasbor',
    'nav.login': 'Masuk',
    'nav.register': 'Daftar',
    'nav.traceability': 'Ketertelusuran',
    'nav.marketplace': 'Pasar',
    'nav.logout': 'Keluar',
    'nav.users': 'Pengguna',
    'nav.orders': 'Pesanan',
    'nav.withdrawals': 'Penarikan',
    'nav.shrimp_types': 'Jenis Udang',
    'nav.shipments': 'Pengiriman',
    'nav.farms': 'Tambak',
    'nav.cultivation': 'Budidaya',
    'nav.harvests': 'Panen',
    'nav.batches': 'Batch',
    'nav.products': 'Produk',
    'nav.sales': 'Penjualan',
    'nav.my_orders': 'Pesanan Saya',
    'nav.cart': 'Keranjang',
    'nav.chat': 'Chat',
    // global
    'global.loading': 'Memuat...',
    'global.search': 'Cari...',
    'global.no_data': 'Data tidak ditemukan.',
    'global.error': 'Masalah',
    'global.error_state': 'Terjadi kesalahan.',
    'global.btn_try_again': 'Coba Lagi',
    'global.empty_state_title': 'Tidak ada data',
    'global.empty_state_msg': 'Belum ada data tersedia.',
    'global.btn_cancel': 'Batal',
    'global.btn_confirm': 'Konfirmasi',
    'global.logout_confirm_title': 'Konfirmasi Keluar',
    'global.logout_confirm_msg': 'Apakah Anda yakin ingin keluar?',
    // landing
    'landing.badge': 'Platform Akuakultur Berbasis Blockchain',
    'landing.title1': 'Crustacean Origin',
    'landing.title2': 'Network Oversight',
    'landing.title3': 'System',
    'landing.subtitle': 'Rantai pasok udang transparan dari tambak ke meja makan. Lacak perjalanan setiap produk dengan teknologi blockchain.',
    'landing.btn_browse': 'Telusuri Pasar',
    'landing.btn_trace': 'Lacak Produk',
    'landing.why_title': 'Mengapa CRONOS?',
    'landing.why_subtitle': 'Ekosistem lengkap yang menghubungkan setiap pemangku kepentingan dalam rantai pasokan budidaya udang.',
    'landing.feat1_title': 'Ketertelusuran Blockchain',
    'landing.feat1_desc': 'Setiap langkah dari tambak ke meja dicatat dengan buku besar blockchain anti-ubah.',
    'landing.feat2_title': 'Transparansi Penuh',
    'landing.feat2_desc': 'Konsumen dapat melacak setiap produk udang kembali ke tambak asalnya.',
    'landing.feat3_title': 'Pelacakan Logistik',
    'landing.feat3_desc': 'Pelacakan pengiriman waktu nyata dari penjemputan hingga lokasi.',
    'landing.feat4_title': 'Pembayaran Digital',
    'landing.feat4_desc': 'Pemrosesan pembayaran aman dengan integrasi Midtrans.',
    'landing.feat5_title': 'Rantai Pasok',
    'landing.feat5_desc': 'Sistem manajemen rantai pasokan akuakultur yang komprehensif.',
    'landing.feat6_title': 'Platform Multi-Peran',
    'landing.feat6_desc': 'Menghubungkan petambak, logistik, konsumen, dan sistem informasi.',
    'landing.how_title': 'Cara Kerjanya',
    'landing.step1': 'Petambak Membuat Udang',
    'landing.step2': 'Batch & Produk Terdaftar',
    'landing.step3': 'Pesanan Konsumen',
    'landing.step4': 'Dikirim & Dilacak',
    'landing.footer': '© 2026 CRONOS — Crustacean Origin Network Oversight System. Seluruh hak cipta.',
    // auth
    'auth.welcome_back': 'Selamat Datang Kembali',
    'auth.signin_sub': 'Masuk ke akun CRONOS Anda',
    'auth.create_account': 'Buat Akun',
    'auth.join_sub': 'Bergabunglah dengan ekosistem CRONOS',
    'auth.email': 'Surel (Email)',
    'auth.password': 'Kata Sandi',
    'auth.full_name': 'Nama Lengkap',
    'auth.phone': 'Nomor Telepon',
    'auth.signing_in': 'Sedang masuk...',
    'auth.sign_in': 'Masuk',
    'auth.creating_account': 'Membuat akun...',
    'auth.btn_register': 'Daftar',
    'auth.no_account': 'Belum punya akun?',
    'auth.has_account': 'Sudah punya akun?',
    // marketplace
    'market.title': 'Pasar Udang Segar',
    'market.subtitle': 'Langsung dari tambak terverifikasi dengan ketertelusuran blockchain',
    'market.placeholder_search': 'Cari produk...',
    'market.filter_all': 'Semua Jenis',
    'market.sort_newest': 'Terbaru',
    'market.sort_price_asc': 'Harga: Rendah ke Tinggi',
    'market.sort_price_desc': 'Harga: Tinggi ke Rendah',
    'market.sort_rating': 'Rating Terbaik',
    'market.err_load': 'Gagal memuat produk',
    'market.loading': 'Memuat produk...',
    'market.empty_title': 'Tidak ada produk',
    'market.empty_desc': 'Belum ada produk tersedia. Silakan cek kembali nanti!',
    'market.add_to_cart': 'Tambah Keranjang',
    // product detail
    'product.back_market': 'Kembali ke Pasar',
    'product.reviews': 'Ulasan',
    'product.err_load': 'Gagal memuat produk',
    'product.not_found': 'Produk tidak ditemukan',
    'product.type': 'Jenis:',
    'product.size': 'Ukuran:',
    'product.stock': 'Stok:',
    'product.batch': 'Batch:',
    'product.farmer': 'Petambak:',
    'product.per': 'per',
    'product.no_reviews': 'Belum ada ulasan.',
    // traceability
    'trace.title': 'Ketertelusuran Produk',
    'trace.subtitle': 'Lacak perjalanan lengkap udang Anda dari tambak ke meja makan',
    'trace.lbl_enter_batch': 'Masukkan Kode Batch',
    'trace.btn_trace': 'Lacak',
    'trace.msg_tracing': 'Melacak produk...',
    'trace.err_not_found': 'Batch tidak ditemukan atau data tidak tersedia',
    'trace.info_title': 'Informasi Batch',
    'trace.lbl_batch': 'Kode Batch:',
    'trace.lbl_qty': 'Kuantitas:',
    'trace.timeline_title': 'Linimasa',
    'trace.lbl_hash': 'Hash:',
    'trace.lbl_by': 'Oleh:',
    'trace.empty_title': 'Tidak Ada Data',
    'trace.empty_desc': 'Data ketertelusuran tidak ditemukan untuk kode batch ini.',
    'trace.event.farm_created': 'Tambak Dibuat',
    'trace.event.cultivation_started': 'Budidaya Dimulai',
    'trace.event.feed_logged': 'Pakan Dicatat',
    'trace.event.water_quality_logged': 'Kualitas Air Dicatat',
    'trace.event.harvest_completed': 'Panen Selesai',
    'trace.event.batch_created': 'Batch Dibuat',
    'trace.event.product_listed': 'Produk Terdaftar',
    'trace.event.order_created': 'Pesanan Dibuat',
    'trace.event.shipment_pickup': 'Pengiriman Dijemput',
    'trace.event.shipment_transit': 'Dalam Perjalanan',
    'trace.event.shipment_delivered': 'Terkirim',
    // admin
    'admin.dashboard.title': 'Dasbor Admin',
    'admin.dashboard.total_users': 'Total Pengguna',
    'admin.dashboard.total_orders': 'Total Pesanan',
    'admin.dashboard.revenue': 'Pendapatan',
    'admin.dashboard.paid_orders': 'Pesanan Dibayar',
    'admin.dashboard.users_by_role': 'Pengguna berdasarkan Peran',
    'admin.dashboard.orders_by_status': 'Pesanan berdasarkan Status',
    'admin.users.title': 'Manajemen Pengguna',
    'admin.users.create_new': 'Buat Pengguna Baru',
    'admin.users.col_name': 'Nama',
    'admin.users.col_email': 'Surel',
    'admin.users.col_role': 'Peran',
    'admin.users.col_status': 'Status',
    'admin.users.col_actions': 'Aksi',
    'admin.users.btn_verify': 'Verifikasi',
    'admin.orders.title': 'Semua Pesanan',
    'admin.orders.col_id': 'ID Pesanan',
    'admin.orders.col_customer': 'Pelanggan',
    'admin.orders.col_amount': 'Jumlah',
    'admin.orders.col_status': 'Status',
    'admin.orders.col_date': 'Tanggal',
    'admin.withdrawals.title': 'Permintaan Penarikan Dana',
    'admin.withdrawals.btn_review': 'Tinjau',
    'admin.withdrawals.modal_title': 'Tinjau Penarikan',
    'admin.withdrawals.btn_reject': 'Tolak',
    'admin.withdrawals.btn_approve': 'Setujui',
    'admin.shrimp_types.title': 'Jenis Udang',
    'admin.shrimp_types.btn_add': 'Tambah Jenis',
    'admin.shrimp_types.btn_delete': 'Hapus',
    'admin.shrimp_types.modal_title': 'Tambah Jenis Udang',
    'admin.shipments.title': 'Manajemen Pengiriman',
    'admin.shipments.btn_create': 'Buat Pengiriman',
    'admin.trace_logs.title': 'Ketertelusuran Blockchain',
    'admin.trace_logs.btn_verify': 'Verifikasi Rantai',
    'admin.trace_logs.msg_valid': 'Integritas rantai blok terverifikasi',
    'admin.trace_logs.msg_invalid': 'Integritas rantai blok terganggu',
    // petambak
    'petambak.dashboard.title': 'Dasbor Petambak',
    'petambak.dashboard.farms': 'Tambak',
    'petambak.dashboard.products': 'Produk',
    'petambak.dashboard.cultivations': 'Budidaya',
    'petambak.dashboard.harvests': 'Panen',
    'petambak.dashboard.revenue': 'Pendapatan',
    'petambak.farms.title': 'Tambak Saya',
    'petambak.farms.btn_add': 'Tambah Tambak',
    'petambak.farms.ponds': 'kolam',
    'petambak.farms.btn_create': 'Buat Tambak',
    'petambak.cultivation.title': 'Siklus Budidaya',
    'petambak.harvests.title': 'Panen',
    'petambak.batches.title': 'Batch',
    'petambak.products.title': 'Produk Saya',
    'petambak.products.btn_add': 'Tambah Produk',
    'petambak.products.btn_create': 'Buat Produk',
    'petambak.sales.title': 'Penjualan',
    'petambak.withdrawals.title': 'Penarikan Dana',
    'petambak.withdrawals.btn_request': 'Ajukan Penarikan',
    'petambak.withdrawals.btn_submit': 'Kirim Pengajuan',
    // logistik
    'logistik.dashboard.title': 'Dasbor Logistik',
    'logistik.dashboard.total_shipments': 'Total Pengiriman',
    'logistik.dashboard.pending': 'Tertunda',
    'logistik.dashboard.in_transit': 'Dalam Perjalanan',
    'logistik.dashboard.delivered': 'Terkirim',
    'logistik.shipments.title': 'Pengiriman Saya',
    'logistik.shipments.btn_update_to': 'Perbarui ke',
    'logistik.shipments.btn_confirm': 'Konfirmasi Pembaruan',
    // konsumen
    'konsumen.dashboard.title': 'Dasbor Konsumen',
    'konsumen.dashboard.total_orders': 'Total Pesanan',
    'konsumen.dashboard.recent_orders': 'Pesanan Terbaru',
    'konsumen.dashboard.view_all': 'Lihat Semua',
    'konsumen.dashboard.no_orders_yet': 'Belum ada pesanan. Kunjungi ',
    'konsumen.dashboard.visit_marketplace': 'pasar',
    'konsumen.orders.title': 'Pesanan Saya',
    'konsumen.orders.btn_pay': 'Bayar',
    'konsumen.orders.btn_cancel': 'Batal',
    'konsumen.orders.btn_review': 'Ulas',
    'konsumen.orders.modal_review_title': 'Tulis Ulasan',
    'konsumen.orders.btn_submit_review': 'Kirim Ulasan',
    'konsumen.orders.total': 'Total:',
    'konsumen.cart.title': 'Keranjang Belanja',
    'konsumen.cart.items': 'barang',
    'konsumen.cart.empty_title': 'Keranjang kosong',
    'konsumen.cart.empty_desc': 'Telusuri pasar untuk menambahkan produk.',
    'konsumen.cart.btn_go_market': 'Pergi ke Pasar',
    'konsumen.cart.summary_title': 'Ringkasan Pesanan',
    'konsumen.cart.subtotal': 'Subtotal',
    'konsumen.cart.shipping': 'Pengiriman',
    'konsumen.cart.calculated': 'Dihitung saat pembayaran',
    'konsumen.cart.total': 'Total',
    'konsumen.cart.btn_checkout': 'Checkout (Pembayaran)',
    'konsumen.checkout.title': 'Pembayaran',
    'konsumen.checkout.order_items': 'Barang Pesanan',
    'konsumen.checkout.total': 'Total',
    'konsumen.checkout.shipping_info': 'Informasi Pengiriman',
    'konsumen.checkout.btn_processing': 'Memproses...',
    'konsumen.checkout.btn_place_order': 'Buat Pesanan & Bayar Rp ',
    // chat
    'chat.messages': 'Pesan',
    'chat.no_rooms': 'Belum ada percakapan.',
    'chat.placeholder': 'Ketik pesan...',
    'chat.select_title': 'Tidak ada chat terpilih',
    'chat.select_msg': 'Pilih percakapan dari sidebar untuk mulai berkirim pesan.',
    'chat.start_new': 'Mulai Percakapan Baru',
    'chat.search_users': 'Cari pengguna berdasarkan nama atau peran...',
  };

  // ─── English ───────────────────────────────────────────
  static const _en = <String, String>{
    'nav.back_to_home': 'Back to Home',
    'nav.dashboard': 'Dashboard',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.traceability': 'Traceability',
    'nav.marketplace': 'Marketplace',
    'nav.logout': 'Logout',
    'nav.users': 'Users',
    'nav.orders': 'Orders',
    'nav.withdrawals': 'Withdrawals',
    'nav.shrimp_types': 'Shrimp Types',
    'nav.shipments': 'Shipments',
    'nav.farms': 'Farms',
    'nav.cultivation': 'Cultivation',
    'nav.harvests': 'Harvests',
    'nav.batches': 'Batches',
    'nav.products': 'Products',
    'nav.sales': 'Sales',
    'nav.my_orders': 'My Orders',
    'nav.cart': 'Cart',
    'nav.chat': 'Chat',
    'global.loading': 'Loading...',
    'global.search': 'Search...',
    'global.no_data': 'No data found.',
    'global.error': 'Error',
    'global.error_state': 'Something went wrong.',
    'global.btn_try_again': 'Try Again',
    'global.empty_state_title': 'No data',
    'global.empty_state_msg': 'No data available yet.',
    'global.btn_cancel': 'Cancel',
    'global.btn_confirm': 'Confirm',
    'global.logout_confirm_title': 'Confirm Logout',
    'global.logout_confirm_msg': 'Are you sure you want to log out?',
    'landing.badge': 'Blockchain-Powered Aquaculture Platform',
    'landing.title1': 'Crustacean Origin',
    'landing.title2': 'Network Oversight',
    'landing.title3': 'System',
    'landing.subtitle': "Transparent shrimp supply chain from farm to table. Trace every product's journey with blockchain technology.",
    'landing.btn_browse': 'Browse Marketplace',
    'landing.btn_trace': 'Trace Product',
    'landing.why_title': 'Why CRONOS?',
    'landing.why_subtitle': 'A complete ecosystem connecting every stakeholder in the shrimp aquaculture supply chain.',
    'landing.feat1_title': 'Blockchain Traceability',
    'landing.feat1_desc': 'Every step from farm to table recorded with tamper-proof blockchain ledger.',
    'landing.feat2_title': 'Full Transparency',
    'landing.feat2_desc': 'Consumers can trace every shrimp product back to its origin farm.',
    'landing.feat3_title': 'Logistics Tracking',
    'landing.feat3_desc': 'Real-time shipment tracking from pickup to delivery.',
    'landing.feat4_title': 'Digital Payments',
    'landing.feat4_desc': 'Secure payment processing with Midtrans gateway integration.',
    'landing.feat5_title': 'Supply Chain',
    'landing.feat5_desc': 'Complete aquaculture supply chain management system.',
    'landing.feat6_title': 'Multi-Role Platform',
    'landing.feat6_desc': 'Connecting farmers, logistics, consumers, and administrators.',
    'landing.how_title': 'How It Works',
    'landing.step1': 'Farm Creates Shrimp',
    'landing.step2': 'Batch & Product Listed',
    'landing.step3': 'Consumer Orders',
    'landing.step4': 'Delivered & Traced',
    'landing.footer': '© 2026 CRONOS — Crustacean Origin Network Oversight System. All rights reserved.',
    'auth.welcome_back': 'Welcome Back',
    'auth.signin_sub': 'Sign in to your CRONOS account',
    'auth.create_account': 'Create Account',
    'auth.join_sub': 'Join the CRONOS ecosystem',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.full_name': 'Full Name',
    'auth.phone': 'Phone',
    'auth.signing_in': 'Signing in...',
    'auth.sign_in': 'Sign In',
    'auth.creating_account': 'Creating account...',
    'auth.btn_register': 'Create Account',
    'auth.no_account': "Don't have an account?",
    'auth.has_account': 'Already have an account?',
    'market.title': 'Fresh Shrimp Marketplace',
    'market.subtitle': 'Direct from verified farms with blockchain traceability',
    'market.placeholder_search': 'Search products...',
    'market.filter_all': 'All Types',
    'market.sort_newest': 'Newest',
    'market.sort_price_asc': 'Price: Low to High',
    'market.sort_price_desc': 'Price: High to Low',
    'market.sort_rating': 'Best Rating',
    'market.err_load': 'Failed to load products',
    'market.loading': 'Loading products...',
    'market.empty_title': 'No products',
    'market.empty_desc': 'No products available yet. Check back later!',
    'market.add_to_cart': 'Add to Cart',
    'product.back_market': 'Back to Marketplace',
    'product.reviews': 'Reviews',
    'product.err_load': 'Failed to load product',
    'product.not_found': 'Product not found',
    'product.type': 'Type:',
    'product.size': 'Size:',
    'product.stock': 'Stock:',
    'product.batch': 'Batch:',
    'product.farmer': 'Farmer:',
    'product.per': 'per',
    'product.no_reviews': 'No reviews yet.',
    'trace.title': 'Product Traceability',
    'trace.subtitle': 'Trace the complete journey of your shrimp from farm to table',
    'trace.lbl_enter_batch': 'Enter Batch Code',
    'trace.btn_trace': 'Trace',
    'trace.msg_tracing': 'Tracing product...',
    'trace.err_not_found': 'Batch not found or no traceability data available',
    'trace.info_title': 'Batch Information',
    'trace.lbl_batch': 'Batch Code:',
    'trace.lbl_qty': 'Quantity:',
    'trace.timeline_title': 'Timeline',
    'trace.lbl_hash': 'Hash:',
    'trace.lbl_by': 'By:',
    'trace.empty_title': 'No Data',
    'trace.empty_desc': 'No traceability data found for this batch code.',
    'trace.event.farm_created': 'Farm Created',
    'trace.event.cultivation_started': 'Cultivation Started',
    'trace.event.feed_logged': 'Feed Logged',
    'trace.event.water_quality_logged': 'Water Quality Logged',
    'trace.event.harvest_completed': 'Harvest Completed',
    'trace.event.batch_created': 'Batch Created',
    'trace.event.product_listed': 'Product Listed',
    'trace.event.order_created': 'Order Created',
    'trace.event.shipment_pickup': 'Shipment Pickup',
    'trace.event.shipment_transit': 'In Transit',
    'trace.event.shipment_delivered': 'Delivered',
    'admin.dashboard.title': 'Admin Dashboard',
    'admin.dashboard.total_users': 'Total Users',
    'admin.dashboard.total_orders': 'Total Orders',
    'admin.dashboard.revenue': 'Revenue',
    'admin.dashboard.paid_orders': 'Paid Orders',
    'admin.dashboard.users_by_role': 'Users by Role',
    'admin.dashboard.orders_by_status': 'Orders by Status',
    'admin.users.title': 'User Management',
    'admin.users.create_new': 'Create New User',
    'admin.users.col_name': 'Name',
    'admin.users.col_email': 'Email',
    'admin.users.col_role': 'Role',
    'admin.users.col_status': 'Status',
    'admin.users.col_actions': 'Actions',
    'admin.users.btn_verify': 'Verify',
    'admin.orders.title': 'All Orders',
    'admin.orders.col_id': 'Order ID',
    'admin.orders.col_customer': 'Customer',
    'admin.orders.col_amount': 'Amount',
    'admin.orders.col_status': 'Status',
    'admin.orders.col_date': 'Date',
    'admin.withdrawals.title': 'Withdrawal Requests',
    'admin.withdrawals.btn_review': 'Review',
    'admin.withdrawals.modal_title': 'Review Withdrawal',
    'admin.withdrawals.btn_reject': 'Reject',
    'admin.withdrawals.btn_approve': 'Approve',
    'admin.shrimp_types.title': 'Shrimp Types',
    'admin.shrimp_types.btn_add': 'Add Type',
    'admin.shrimp_types.btn_delete': 'Delete',
    'admin.shrimp_types.modal_title': 'Add Shrimp Type',
    'admin.shipments.title': 'Shipment Management',
    'admin.shipments.btn_create': 'Create Shipment',
    'admin.trace_logs.title': 'Blockchain Traceability',
    'admin.trace_logs.btn_verify': 'Verify Chain',
    'admin.trace_logs.msg_valid': 'Blockchain chain integrity verified',
    'admin.trace_logs.msg_invalid': 'Chain integrity compromised',
    'petambak.dashboard.title': 'Petambak Dashboard',
    'petambak.dashboard.farms': 'Farms',
    'petambak.dashboard.products': 'Products',
    'petambak.dashboard.cultivations': 'Cultivations',
    'petambak.dashboard.harvests': 'Harvests',
    'petambak.dashboard.revenue': 'Revenue',
    'petambak.farms.title': 'My Farms',
    'petambak.farms.btn_add': 'Add Farm',
    'petambak.farms.ponds': 'ponds',
    'petambak.farms.btn_create': 'Create Farm',
    'petambak.cultivation.title': 'Cultivation Cycles',
    'petambak.harvests.title': 'Harvests',
    'petambak.batches.title': 'Batches',
    'petambak.products.title': 'My Products',
    'petambak.products.btn_add': 'Add Product',
    'petambak.products.btn_create': 'Create Product',
    'petambak.sales.title': 'Sales',
    'petambak.withdrawals.title': 'Withdrawals',
    'petambak.withdrawals.btn_request': 'Request Withdrawal',
    'petambak.withdrawals.btn_submit': 'Submit Request',
    'logistik.dashboard.title': 'Logistics Dashboard',
    'logistik.dashboard.total_shipments': 'Total Shipments',
    'logistik.dashboard.pending': 'Pending',
    'logistik.dashboard.in_transit': 'In Transit',
    'logistik.dashboard.delivered': 'Delivered',
    'logistik.shipments.title': 'My Shipments',
    'logistik.shipments.btn_update_to': 'Update to',
    'logistik.shipments.btn_confirm': 'Confirm Update',
    'konsumen.dashboard.title': 'Consumer Dashboard',
    'konsumen.dashboard.total_orders': 'Total Orders',
    'konsumen.dashboard.recent_orders': 'Recent Orders',
    'konsumen.dashboard.view_all': 'View All',
    'konsumen.dashboard.no_orders_yet': 'No orders yet. Visit the ',
    'konsumen.dashboard.visit_marketplace': 'marketplace',
    'konsumen.orders.title': 'My Orders',
    'konsumen.orders.btn_pay': 'Pay',
    'konsumen.orders.btn_cancel': 'Cancel',
    'konsumen.orders.btn_review': 'Review',
    'konsumen.orders.modal_review_title': 'Write Review',
    'konsumen.orders.btn_submit_review': 'Submit Review',
    'konsumen.orders.total': 'Total:',
    'konsumen.cart.title': 'Shopping Cart',
    'konsumen.cart.items': 'items',
    'konsumen.cart.empty_title': 'Cart is empty',
    'konsumen.cart.empty_desc': 'Browse the marketplace to add products.',
    'konsumen.cart.btn_go_market': 'Go to Marketplace',
    'konsumen.cart.summary_title': 'Order Summary',
    'konsumen.cart.subtotal': 'Subtotal',
    'konsumen.cart.shipping': 'Shipping',
    'konsumen.cart.calculated': 'Calculated at checkout',
    'konsumen.cart.total': 'Total',
    'konsumen.cart.btn_checkout': 'Checkout',
    'konsumen.checkout.title': 'Checkout',
    'konsumen.checkout.order_items': 'Order Items',
    'konsumen.checkout.total': 'Total',
    'konsumen.checkout.shipping_info': 'Shipping Information',
    'konsumen.checkout.btn_processing': 'Processing...',
    'konsumen.checkout.btn_place_order': 'Place Order & Pay Rp ',
    'chat.messages': 'Messages',
    'chat.no_rooms': 'No conversations yet.',
    'chat.placeholder': 'Type a message...',
    'chat.select_title': 'No chat selected',
    'chat.select_msg': 'Choose a conversation from the sidebar to start chatting.',
    'chat.start_new': 'Start New Conversation',
    'chat.search_users': 'Search users by name or role...',
  };

  // ─── Dutch (Nederlands) ────────────────────────────────
  static const _nl = <String, String>{
    'nav.back_to_home': 'Terug naar Home',
    'nav.dashboard': 'Dashboard',
    'nav.login': 'Inloggen',
    'nav.register': 'Registreren',
    'nav.traceability': 'Traceerbaarheid',
    'nav.marketplace': 'Marktplaats',
    'nav.logout': 'Uitloggen',
    'nav.users': 'Gebruikers',
    'nav.orders': 'Bestellingen',
    'nav.withdrawals': 'Opnames',
    'nav.shrimp_types': 'Garnalensoorten',
    'nav.shipments': 'Verzendingen',
    'nav.farms': 'Boerderijen',
    'nav.cultivation': 'Teelt',
    'nav.harvests': 'Oogsten',
    'nav.batches': 'Batches',
    'nav.products': 'Producten',
    'nav.sales': 'Verkoop',
    'nav.my_orders': 'Mijn Bestellingen',
    'nav.cart': 'Winkelwagen',
    'nav.chat': 'Chat',
    'global.loading': 'Laden...',
    'global.btn_cancel': 'Annuleren',
    'global.btn_confirm': 'Bevestigen',
    'global.logout_confirm_title': 'Bevestig Uitloggen',
    'global.logout_confirm_msg': 'Weet u zeker dat u wilt uitloggen?',
    'landing.badge': 'Blockchain-Aangedreven Aquacultuur Platform',
    'landing.title1': 'Crustacean Origin',
    'landing.title2': 'Network Oversight',
    'landing.title3': 'System',
    'landing.subtitle': 'Transparante garnalenketen van boerderij tot tafel. Volg de reis van elk product met blockchain-technologie.',
    'landing.btn_browse': 'Marktplaats Verkennen',
    'landing.btn_trace': 'Product Traceren',
    'landing.why_title': 'Waarom CRONOS?',
    'landing.footer': '© 2026 CRONOS — Crustacean Origin Network Oversight System. Alle rechten voorbehouden.',
    'auth.welcome_back': 'Welkom Terug',
    'auth.signin_sub': 'Log in op uw CRONOS-account',
    'auth.sign_in': 'Inloggen',
    'auth.create_account': 'Account Aanmaken',
    'auth.email': 'E-mail',
    'auth.password': 'Wachtwoord',
    'auth.full_name': 'Volledige Naam',
    'auth.phone': 'Telefoon',
    'chat.messages': 'Berichten',
    'chat.placeholder': 'Typ een bericht...',
    'chat.start_new': 'Nieuw Gesprek Starten',
  };
}
